<?php

/**
 * @file
 * Contains mouski.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mouski_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mouski module.
    case 'help.page.mouski':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mouski_theme() {
  return [
    'mouski' => [
      'variables' => [
        'attributes' => [],
        'users' => '',
      ],
    ],
  ];
}
